### ISSUE TITLE
Location setting

### ISSUE THREAD

**Issue by oasalonen** [oasalonen/RealityPacman#15]
Allow user to enable/disable location API. Required for app cert.

**Comment by omahlama** [comment]
Is it really necessary to allow user to disable location API? This application is useless without it. I thought that it would be enough to just show a nice error message to user that doesn't have location service enabled.

**Comment by oasalonen** [comment]
See point 2.7.3 in the application certification policies:

http://msdn.microsoft.com/en-us/library/hh184841%28v=VS.92%29.aspx

I agree it's dumb. The question is, do we want to test how literally they take those policies?

**Comment by omahlama** [comment]
Ok, so add a checkbox that says "Enable location API", if the user turns it off just prevent starting a new game.

**Comment by oasalonen** [comment]
Done.
