### ISSUE TITLE
Create application icon

### ISSUE THREAD

**Issue by omahlama** [oasalonen/RealityPacman#5]
Needed for app hub approval. Size is 173X173 and 99x99 pixels.

**Comment by omahlama** [comment]
Icons don't work well as they are now, because the background is the system color, eg. red or green. I'll attach screen shots when I find out how to do it in github.

The 173x image you created is actually 174px, so doesn't pass the marketplace test.

We also need a 62x62 pixel application icon.

**Comment by omahlama** [comment]
I actually read the marketplace docs and now I know what we need as Icons:

99x99, 173x173 and 200x200 non transparent png for the website (list, grid and page)

62x62 and 173x173 possibly transparent png for the phone. The current ones don't work, as the background is the phone default color, e.g. red or green. Maybe just different shades of white and black. Or then do a non transparent icon shaped like a square.

**Comment by omahlama** [comment]
Screen shots of icon from emulator are in the project, under screen shots -folder.

**Comment by tehmou** [comment]
Ok, I will have a look at this. I will also try to remember to check the market place website to see where they actually end up.

**Comment by tehmou** [comment]
Accidentally closed :D

**Comment by tehmou** [comment]
New icons are now in repository.
