### ISSUE TITLE
Update position more frequently

### ISSUE THREAD

**Issue by ovan** [oasalonen/RealityPacman#7]
In tight spots running away from ghosts is sometimes frustrating because position update's take few seconds. For example switching to running and then been caught because the app didn't notice doesn't reward you nicely. Could we get the gps position more often? Or could we keep track speed and direction or acceleration and use those to extrapolate position between actual gps updates?

**Comment by oasalonen** [comment]
When did you test this? A few days after the initial version, I decreased the GPS minimum update threshold to 5 meters. This should improve the situation, but I haven't had a chance to verify.

**Comment by ovan** [comment]
Ok, I'll test again and report back.
