### ISSUE TITLE
Add handling of gps state

### ISSUE THREAD

**Issue by omahlama** [oasalonen/RealityPacman#8]
Needed for marketplace: add error message when user has disabled positioning services.

Implement change so that game is paused when user doesn't have positioning fix.

**Comment by omahlama** [comment]
http://msdn.microsoft.com/en-us/library/ff431782%28v=VS.92%29.aspx

**Comment by oasalonen** [comment]
There is now a positioning status bar at the top of the map that is visible when GPS is disabled or a fix is not yet available.

Still needs pause while no fix and better graphics for a GPS status icon.

**Comment by oasalonen** [comment]
Latest version has graphics for different GPS states.

**Comment by oasalonen** [comment]
Game starts only when the device gets the first location.
